# Generated by Django 4.1.7 on 2023-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('SP', 'Sport'), ('EC', 'Economy'), ('AR', 'Art')], default='EC', max_length=2),
        ),
    ]
