# Generated by Django 4.1.7 on 2023-04-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
