# Generated by Django 4.1.7 on 2023-05-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='article_images/'),
        ),
    ]
